// Auto-generated from uploaded_image_links.txt
export const assetsImage: Record<string, string> = {
  "d0_HiddenValley.png": "https://i.ibb.co/m5m3gcVP/d0-Hidden-Valley.png",
  "d0_Village.png": "https://i.ibb.co/0ykHp4Tj/d0-Village.png",
  "d62_Bunker.png": "https://i.ibb.co/20dvcZdf/d62-Bunker.png",
  "d62_StartWizardTower.png": "https://i.ibb.co/mFghWnKb/d62-Start-Wizard-Tower.png",
  "d75_Sunset.png": "https://i.ibb.co/yFLNYTtH/d75-Sunset.png",
  "d93_MysteriousValley01.png": "https://i.ibb.co/WNMBpkn0/d93-Mysterious-Valley01.png",
  "d93_MysteriousValley02.png": "https://i.ibb.co/KzBBXfHX/d93-Mysterious-Valley02.png",
  "d93_ViewBellowFortess.png": "https://i.ibb.co/1YPDqyz8/d93-View-Bellow-Fortess.png",
  "d94_PolarBearFriend.png": "https://i.ibb.co/G642H1f/d94-Polar-Bear-Friend.png",
  "d94_TunnelOfSteepness.png": "https://i.ibb.co/9kgZsMV3/d94-Tunnel-Of-Steepness.png",
  "d120_MoreCavesWithZombie.png": "https://i.ibb.co/wFJzXBRZ/d120-More-Caves-With-Zombie.png",
  "d124_HiddenLamba.png": "https://i.ibb.co/zWswKMLY/d124-Hidden-Lamba.png",
  "d129_MoonWaterfall.png": "https://i.ibb.co/zhfL6mFn/d129-Moon-Waterfall.png",
  "d131_MysteriousGoo.png": "https://i.ibb.co/R4ZBFBfX/d131-Mysterious-Goo.png",
  "d147_ReturnGoo.png": "https://i.ibb.co/ksTdK69d/d147-Return-Goo.png",
  "d147_TreatureInTheDark.png": "https://i.ibb.co/WNXxp3gy/d147-Treature-In-The-Dark.png",
  "d151_FortessViewSunset.png": "https://i.ibb.co/SDYKtqTj/d151-Fortess-View-Sunset.png",
  "d152_Boat.png": "https://i.ibb.co/fVD11kTT/d152-Boat.png",
  "d152_VillageViewWaterBoat.png": "https://i.ibb.co/93bKrHvV/d152-Village-View-Water-Boat.png",
  "d153_2Villagers.png": "https://i.ibb.co/pvx8wJpK/d153-2-Villagers.png",
  "d153_SnowVillage.png": "https://i.ibb.co/R4NbySKV/d153-Snow-Village.png",
  "d156_PortalStrayBattle.png": "https://i.ibb.co/99mGvSNN/d156-Portal-Stray-Battle.png",
  "d157_AfterStrayBattle.png": "https://i.ibb.co/KjNjNqNm/d157-After-Stray-Battle.png",
  "d158_TaigaVillage.png": "https://i.ibb.co/hx74WvqG/d158-Taiga-Village.png",
  "d170_TwoPolarBears_HappyFlippy.png": "https://i.ibb.co/xKK7vxZB/d170-Two-Polar-Bears-Happy-Flippy.png",
  "d175_BuildingTower.png": "https://i.ibb.co/XrTKYWjN/d175-Building-Tower.png",
  "d175_TowerBelow.png": "https://i.ibb.co/hxpqMf8D/d175-Tower-Below.png",
  "d175_ViewExpandedVillage.png": "https://i.ibb.co/d0cbrrYC/d175-View-Expanded-Village.png",
  "d181_FortessView.png": "https://i.ibb.co/V0MSz6wV/d181-Fortess-View.png",
  "d181_GoieHorse.png": "https://i.ibb.co/4gXRXBxY/d181-Goie-Horse.png",
  "d197_LavaPit.png": "https://i.ibb.co/21B9Rd8F/d197-Lava-Pit.png",
  "d208_FortessView.png": "https://i.ibb.co/F42kLDNW/d208-Fortess-View.png",
  "d217_FirstTowerLookBelow.png": "https://i.ibb.co/Q09mtCt/d217-First-Tower-Look-Below.png",
  "d222_MapRoom.png": "https://i.ibb.co/TNtjW2C/d222-Map-Room.png"
};
